"""Public domain contracts for FakeDetector."""

from fakedetector.domain.enums import (
    AnalysisStatus,
    AnalyzerStatus,
    CleanupStatus,
    CompletenessStatus,
    FindingSeverity,
    MediaType,
    ProcessingStage,
    RiskLevel,
    SourceChannel,
)
from fakedetector.domain.models import (
    AnalysisCompleteness,
    AnalyzerResult,
    AudioTechnicalParameters,
    BoundingBoxLocalization,
    ErrorDetail,
    FileLocalization,
    Finding,
    FrameIntervalLocalization,
    ImageTechnicalParameters,
    InputFileDescriptor,
    Localization,
    SourceContext,
    TimeIntervalLocalization,
    ValidatedFileDescriptor,
    ValidationCheck,
    ValidationResult,
    VideoTechnicalParameters,
)

__all__ = [
    "AnalysisCompleteness",
    "AnalysisStatus",
    "AnalyzerResult",
    "AnalyzerStatus",
    "AudioTechnicalParameters",
    "BoundingBoxLocalization",
    "CleanupStatus",
    "CompletenessStatus",
    "ErrorDetail",
    "FileLocalization",
    "Finding",
    "FindingSeverity",
    "FrameIntervalLocalization",
    "ImageTechnicalParameters",
    "InputFileDescriptor",
    "Localization",
    "MediaType",
    "ProcessingStage",
    "RiskLevel",
    "SourceChannel",
    "SourceContext",
    "TimeIntervalLocalization",
    "ValidatedFileDescriptor",
    "ValidationCheck",
    "ValidationResult",
    "VideoTechnicalParameters",
]
